version: "3.9"
services:
  api:
    build: .
    container_name: rickmorty_api
    ports:
      - "4000:4000"
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  db:
    image: postgres:15
    container_name: rickmorty_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: rickmorty_redis
    ports:
      - "6379:6379"
volumes:
  pgdata:
